# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:

# Setup
title: Aquent Gymnasium Press Releases
url: "http://gymnasium.github.io/pr"
baseurl: /pr
future: false
# Custom vars

# version:             1.0.0

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: / # does not include hostname
# show_dir_listing: false

# Outputting
#permalink:     none
#paginate_path: /page:num
#timezone:      null

# quiet:    false
# verbose:  false
# defaults: []
#
# liquid:
#   error_mode: warn
#
# # Markdown Processors
#
# kramdown:
#   auto_ids:       true
#   footnote_nr:    1
#   entity_output:  as_char
#   toc_levels:     1..6
#   smart_quotes:   lsquo,rsquo,ldquo,rdquo
#   input:          GFM
#   hard_wrap:      false
#   footnote_nr:    1
